[pytest]
asyncio_mode = auto
pythonpath = .
testpaths = app/tests
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning:pytest_asyncio.plugin

markers =
    unit: Unit tests
    integration: Integration tests
    api: API tests

addopts = -v --strict-markers